AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false